"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Activity,AlertTriangle,CheckCircle,Clock3,MapPinned,Radio,RefreshCw,RotateCcw,Siren,Truck} from "lucide-react";
import MapView from "@/components/Map";
import type {Incident,RescueUnit,Report} from "@/lib/types";
import {freshDemoState,loadDemoState,saveDemoState} from "@/lib/demo-data";
import {haversine} from "@/lib/analysis";

const PRIORITY_LABEL={CRITICAL:"RED",HIGH:"ORANGE",MEDIUM:"YELLOW",LOW:"GREEN"} as const;
const PRIORITY_ORDER={CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3} as const;

export default function Dispatcher(){
 const[incidents,setIncidents]=useState<Incident[]>([]);const[units,setUnits]=useState<RescueUnit[]>([]);const[reports,setReports]=useState<Report[]>([]);const[selected,setSelected]=useState<Incident>();const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(()=>{const s=loadDemoState();setIncidents(s.incidents);setUnits(s.units);setReports(s.reports);setSelected(old=>old?s.incidents.find(i=>i.id===old.id):undefined)},[]);
 useEffect(()=>{load();const onStorage=()=>load();window.addEventListener("storage",onStorage);const timer=window.setInterval(load,1000);return()=>{window.removeEventListener("storage",onStorage);window.clearInterval(timer)}},[load]);
 const active=useMemo(()=>incidents.filter(i=>i.status!=="RESOLVED").sort((a,b)=>PRIORITY_ORDER[a.severity]-PRIORITY_ORDER[b.severity]||new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()),[incidents]);
 const critical=active.filter(i=>i.severity==="CRITICAL"),available=units.filter(u=>u.status==="AVAILABLE");
 const red=active.filter(i=>i.severity==="CRITICAL").length,orange=active.filter(i=>i.severity==="HIGH").length,yellow=active.filter(i=>i.severity==="MEDIUM").length,green=active.filter(i=>i.severity==="LOW").length;
 const selectedReports=selected?reports.filter(r=>r.incident_id===selected.id):[];
 const nearest=useMemo(()=>{if(!selected)return undefined;return units.filter(u=>u.status==="AVAILABLE").sort((a,b)=>haversine(a.latitude,a.longitude,selected.latitude,selected.longitude)-haversine(b.latitude,b.longitude,selected.latitude,selected.longitude))[0]},[selected,units]);
 const dispatch=()=>{if(!selected||!nearest)return;setBusy(true);const s=loadDemoState();const unit=s.units.find(u=>u.id===nearest.id)!;const incident=s.incidents.find(i=>i.id===selected.id)!;const now=new Date().toISOString();unit.status="ASSIGNED";unit.current_incident_id=incident.id;unit.updated_at=now;incident.status="DISPATCHED";incident.updated_at=now;s.dispatches.push({id:crypto.randomUUID(),incident_id:incident.id,unit_id:unit.id,assigned_at:now,status:"ASSIGNED"});saveDemoState(s);setMessage(unit.name+" dispatched successfully.");setBusy(false);load()};
 const reset=()=>{saveDemoState(freshDemoState());setSelected(undefined);setMessage("Demo data reset.");load()};
 return <main className="command"><header className="topbar"><Link href="/" className="brand"><Siren/> DISASTERMESH</Link><div className="system"><span className="dot"/> LOCAL DEMO COMMAND CENTER</div><div className="top-actions"><Link href="/citizen">Citizen SOS</Link><button onClick={load}><RefreshCw size={15}/> Refresh</button><button onClick={reset}><RotateCcw size={15}/> Reset demo</button></div></header>
 <div className="priority-strip"><div className="priority-title"><Siren size={15}/> PRIORITY QUEUE <span>Highest urgency first</span></div><div className="priority-cards"><div className="priority-card red"><span>RED</span><b>{red}</b><small>CRITICAL</small></div><div className="priority-card orange"><span>ORANGE</span><b>{orange}</b><small>HIGH</small></div><div className="priority-card yellow"><span>YELLOW</span><b>{yellow}</b><small>MEDIUM</small></div><div className="priority-card green"><span>GREEN</span><b>{green}</b><small>LOW</small></div></div></div>
 <div className="stats"><div><Activity/><span>ACTIVE INCIDENTS</span><b>{active.length}</b></div><div><AlertTriangle/><span>CRITICAL</span><b>{critical.length}</b></div><div><Truck/><span>AVAILABLE UNITS</span><b>{available.length}</b></div><div><Radio/><span>REPORTS</span><b>{reports.length}</b></div></div>
 <div className="workspace"><aside className="incident-list"><div className="panel-title">LIVE INCIDENTS <span>{active.length}</span></div>{active.map(i=><button key={i.id} className={selected?.id===i.id?"incident-card selected":"incident-card"} onClick={()=>setSelected(i)}><div><strong className={i.severity.toLowerCase()}>{PRIORITY_LABEL[i.severity]} • {i.severity}</strong><small>{i.status}</small></div><b>{i.title}</b><span><MapPinned size={13}/> {i.location_text} • {i.report_count} reports</span><time><Clock3 size={12}/> {new Date(i.updated_at).toLocaleTimeString()}</time></button>)}{!active.length&&<p className="muted">No active incidents.</p>}</aside><section className="map-panel"><MapView incidents={active} units={units} onIncident={setSelected}/><div className="legend"><b>PRIORITY LEGEND</b><span><i className="critical"/> RED • Critical</span><span><i className="high"/> ORANGE • High</span><span><i className="medium"/> YELLOW • Medium</span><span><i className="low"/> GREEN • Low</span><span>🚑 Rescue unit</span></div></section><aside className="detail">{selected?<><div className="detail-head"><span className={"severity "+selected.severity.toLowerCase()}>{PRIORITY_LABEL[selected.severity]} • {selected.severity}</span><span>{selected.status}</span></div><h2>{selected.title}</h2><p className="location"><MapPinned/> {selected.location_text}</p><div className="score"><span>Severity score</span><b>{selected.severity_score}</b></div><div className="reasons"><b>WHY THIS PRIORITY</b>{selected.severity_reasons.map(r=><div key={r}>• {r}</div>)}</div><div className="meta"><span>Reports <b>{selected.report_count}</b></span><span>Coordinates <b>{selected.latitude.toFixed(4)}, {selected.longitude.toFixed(4)}</b></span></div><div className="timeline"><b>REPORT TIMELINE</b>{selectedReports.slice(0,5).map(r=><div key={r.id}><span>{r.source}</span><p>{r.description}</p><small>{new Date(r.created_at).toLocaleTimeString()}</small></div>)}</div>{nearest&&selected.status!=="DISPATCHED"&&selected.status!=="RESOLVED"&&<div className="dispatch-box"><b>RECOMMENDED UNIT</b><span>{nearest.name}</span><small>{nearest.type} • nearest AVAILABLE unit</small><button disabled={busy} onClick={dispatch}>{busy?"DISPATCHING…":"ASSIGN NEAREST AVAILABLE UNIT"} <Truck size={16}/></button></div>}{message&&<div className="toast"><CheckCircle size={16}/> {message}</div>}</>:<div className="empty"><Siren size={40}/><h2>Select an incident</h2><p>Choose a marker or incident card to triage and dispatch.</p></div>}</aside></div></main>
}
