"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Mic,MapPin,Send,Siren,Upload,WifiOff,Phone} from "lucide-react";
import type {Category,Incident,Report} from "@/lib/types";
import {analyze,extractLocation,haversine} from "@/lib/analysis";
import {loadDemoState,saveDemoState} from "@/lib/demo-data";
import {ZONES,addNotification,saveOfflineReport} from "@/lib/emergency";

export default function Citizen(){
 const[category,setCategory]=useState<Category>("FIRE"); const[text,setText]=useState("Fire spreading near Tambaram railway station. People are trapped inside the building and need immediate rescue.");
 const[lat,setLat]=useState<number>();const[lng,setLng]=useState<number>();const[recording,setRecording]=useState(false);const[result,setResult]=useState<any>();const[loading,setLoading]=useState(false);const[sent,setSent]=useState(false);
 const[evidence,setEvidence]=useState<File[]>([]);const[contacts,setContacts]=useState("");const[online,setOnline]=useState(true);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync)}},[]);
 function locate(){navigator.geolocation?.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude)},()=>alert("Location permission unavailable. Demo location fallback will be used."))}
 function voice(){const SR:any=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert("Voice input is not supported here. You can type normally.");return}const r=new SR();r.lang="en-IN";r.onstart=()=>setRecording(true);r.onend=()=>setRecording(false);r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.start()}
 function chooseEvidence(e:React.ChangeEvent<HTMLInputElement>){setEvidence(Array.from(e.target.files||[]).slice(0,5))}
 function submit(e:React.FormEvent){
  e.preventDefault();setLoading(true);setSent(false);setResult(undefined);const a=analyze(text,category);const loc=extractLocation(text,typeof lat==="number"?lat:undefined,typeof lng==="number"?lng:undefined);const evidenceNames=evidence.map(f=>f.name);const createdAt=new Date().toISOString();const isOffline=!navigator.onLine;
  if(isOffline){saveOfflineReport({category,text,lat:loc.latitude,lng:loc.longitude,evidence:evidenceNames,contacts,created_at:createdAt,status:"QUEUED_OFFLINE"});addNotification("SOS queued offline and will be synced when connection returns.");setLoading(false);setSent(true);setResult({offline:true,priority:a.severity==="CRITICAL"?"RED":a.severity==="HIGH"?"ORANGE":a.severity==="MEDIUM"?"YELLOW":"GREEN",analysis:a,location:loc,evidence:evidenceNames});return}
  const state=loadDemoState();const match=state.incidents.filter(i=>i.status!=="RESOLVED"&&i.category===category).map(i=>({i,d:haversine(i.latitude,i.longitude,loc.latitude,loc.longitude)})).filter(x=>x.d<=500).sort((a,b)=>a.d-b.d)[0];let incidentId:string;let distance:number|undefined;
  if(match){incidentId=match.i.id;distance=match.d;const target=state.incidents.find(i=>i.id===incidentId)!;target.report_count+=1;target.updated_at=createdAt;target.evidence=[...(target.evidence||[]),...evidenceNames];target.status_history=[...(target.status_history||[]),{status:"REPORT_RECEIVED",at:createdAt}];if(a.score>target.severity_score){target.severity=a.severity;target.severity_score=a.score;target.severity_reasons=a.reasons}}
  else{incidentId=crypto.randomUUID();const newIncident:Incident={id:incidentId,title:category+" near "+loc.location_text,category,description:text,latitude:loc.latitude,longitude:loc.longitude,location_text:loc.location_text,severity:a.severity,severity_score:a.score,severity_reasons:a.reasons,report_count:1,status:"NEW",created_at:createdAt,updated_at:createdAt,evidence:evidenceNames,status_history:[{status:"NEW",at:createdAt}]};state.incidents.unshift(newIncident)}
  const reportId=crypto.randomUUID();const report:Report={id:reportId,incident_id:incidentId,description:text,source:"text",latitude:loc.latitude,longitude:loc.longitude,location_text:loc.location_text,severity:a.severity,severity_score:a.score,severity_reasons:a.reasons,created_at:createdAt,evidence:evidenceNames};state.reports.unshift(report);saveDemoState(state);addNotification("New SOS received at "+loc.location_text);
  if(typeof Notification!=="undefined"&&Notification.permission==="granted")new Notification("DisasterMesh SOS",{body:"Emergency report sent to command center."});
  const nearbyZone=ZONES.map(z=>({...z,d:haversine(z.latitude,z.longitude,loc.latitude,loc.longitude)})).filter(z=>z.d<=z.radius).sort((a,b)=>a.d-b.d)[0];
  setLoading(false);setSent(true);setResult({incident_id:incidentId,report_id:reportId,matched:Boolean(match),distance_m:distance,analysis:a,location:loc,priority:a.severity==="CRITICAL"?"RED":a.severity==="HIGH"?"ORANGE":a.severity==="MEDIUM"?"YELLOW":"GREEN",evidence:evidenceNames,nearbyZone,contacts:contacts?contacts.split(",").map(x=>x.trim()).filter(Boolean):[]});
 }
 return <main className="citizen"><header><Link href="/" className="back"><ArrowLeft/> DisasterMesh</Link><span className="live"><i/> {online?"SYSTEM ONLINE":"OFFLINE QUEUE ACTIVE"}</span></header><section className="sos-card"><div className="sos-head"><div><span className="eyebrow">CITIZEN DISTRESS REPORT</span><h1>Send an SOS</h1><p>Your report is analyzed, clustered and sent to the command center.</p></div><div className="siren">{online?<Siren size={34}/>:<WifiOff size={34}/>}</div></div><form onSubmit={submit}><label>Emergency category<select value={category} onChange={e=>setCategory(e.target.value as Category)}><option>FLOOD</option><option>FIRE</option><option>MEDICAL</option><option>BUILDING COLLAPSE</option><option>ROAD BLOCKAGE</option><option>OTHER</option></select></label><label>What is happening?<textarea value={text} onChange={e=>setText(e.target.value)} rows={6}/></label><div className="row"><button type="button" className="tool" onClick={voice}><Mic/> {recording?"Listening…":"Voice input"}</button><button type="button" className="tool" onClick={locate}><MapPin/> Use my location</button><button type="button" className="tool" onClick={()=>fileRef.current?.click()}><Upload/> Evidence {evidence.length ? "(" + evidence.length + ")" : ""}</button><input ref={fileRef} type="file" accept="image/*,video/*" multiple hidden onChange={chooseEvidence}/></div><label><Phone/> Emergency contacts <small>(comma-separated)</small><input value={contacts} onChange={e=>setContacts(e.target.value)} placeholder="9876543210, 9123456780"/></label>{!online&&<div className="offline-note"><WifiOff size={16}/> No internet — SOS will be queued safely on this device.</div>}<button className="send" disabled={loading||sent}><Send/> {loading?"SENDING SOS…":sent?"SOS SENT ✓":"SEND SOS"}</button></form>{result&&<div className="result"><div className="result-top"><b>{result.offline?"✓ SOS QUEUED OFFLINE":"✓ SOS SENT SUCCESSFULLY"}</b><span>{result.priority} • {result.offline?"QUEUED":"PENDING"} • WAITING FOR DISPATCHER</span></div><p><strong>Location:</strong> {result.location.location_text}</p><p><strong>Status:</strong> {result.offline?"Saved offline and ready to sync when connection returns.":"Your SOS has been sent to the command center."}</p><p><strong>Priority reason:</strong> {result.analysis.reasons.join(" • ")}</p>{result.evidence?.length>0&&<p><strong>Evidence:</strong> {result.evidence.join(", ")}</p>}{result.contacts?.length>0&&<p><strong>Emergency contacts:</strong> notified in demo mode.</p>}{result.nearbyZone&&<p><strong>Zone:</strong> {result.nearbyZone.type==="DANGER"?"⚠️ Danger":"🛡️ Safe"} — {result.nearbyZone.name}</p>}{result.matched&&<p><strong>500m cluster:</strong> {Math.round(result.distance_m)}m away • report added to existing incident</p>}{!result.offline&&<small>Incident: {result.incident_id} • Report: {result.report_id}</small>}</div>}</section></main>
}