"use client";import {useState} from "react";import Link from "next/link";import {ArrowLeft,Mic,MapPin,Send,Siren,Upload} from "lucide-react";import type {Category, Incident, Report} from "@/lib/types";
import {analyze,extractLocation,haversine} from "@/lib/analysis";
import {loadDemoState,saveDemoState} from "@/lib/demo-data";
export default function Citizen(){
 const[category,setCategory]=useState<Category>("FIRE"); const[text,setText]=useState("Fire spreading near Tambaram railway station. People are trapped inside the building and need immediate rescue.");
 const[lat,setLat]=useState<number>(); const[lng,setLng]=useState<number>(); const[recording,setRecording]=useState(false); const[result,setResult]=useState<any>(); const[loading,setLoading]=useState(false); const[sent,setSent]=useState(false);
 function locate(){navigator.geolocation?.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude)},()=>alert("Location permission unavailable. Demo location fallback will be used."))}
 function voice(){const SR:any=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){alert("Voice input is not supported here. You can type normally.");return}const r=new SR();r.lang="en-IN";r.onstart=()=>setRecording(true);r.onend=()=>setRecording(false);r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.start()}
 function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setSent(false);setResult(undefined);const a=analyze(text,category);const loc=extractLocation(text,typeof lat==="number"?lat:undefined,typeof lng==="number"?lng:undefined);const state=loadDemoState();const match=state.incidents.filter(i=>i.status!=="RESOLVED"&&i.category===category).map(i=>({i,d:haversine(i.latitude,i.longitude,loc.latitude,loc.longitude)})).filter(x=>x.d<=500).sort((a,b)=>a.d-b.d)[0];const createdAt=new Date().toISOString();let incidentId:string;let distance:number|undefined;if(match){incidentId=match.i.id;distance=match.d;const target=state.incidents.find(i=>i.id===incidentId)!;target.report_count+=1;target.updated_at=createdAt;if(a.score>target.severity_score){target.severity=a.severity;target.severity_score=a.score;target.severity_reasons=a.reasons}}else{incidentId=crypto.randomUUID();const newIncident:Incident={id:incidentId,title:category+" near "+loc.location_text,category,description:text,latitude:loc.latitude,longitude:loc.longitude,location_text:loc.location_text,severity:a.severity,severity_score:a.score,severity_reasons:a.reasons,report_count:1,status:"NEW",created_at:createdAt,updated_at:createdAt};state.incidents.unshift(newIncident)}const reportId=crypto.randomUUID();const report:Report={id:reportId,incident_id:incidentId,description:text,source:"text",latitude:loc.latitude,longitude:loc.longitude,location_text:loc.location_text,severity:a.severity,severity_score:a.score,severity_reasons:a.reasons,created_at:createdAt};state.reports.unshift(report);saveDemoState(state);setLoading(false);setSent(true);setResult({incident_id:incidentId,report_id:reportId,matched:Boolean(match),distance_m:distance,analysis:a,location:loc,priority:a.severity==="CRITICAL"?"RED":a.severity==="HIGH"?"ORANGE":a.severity==="MEDIUM"?"YELLOW":"GREEN"})}
 return <main className="citizen"><header><Link href="/" className="back"><ArrowLeft/> DisasterMesh</Link><span className="live"><i/> SYSTEM READY</span></header><section className="sos-card"><div className="sos-head"><div><span className="eyebrow">CITIZEN DISTRESS REPORT</span><h1>Send an SOS</h1><p>Your report is analyzed, clustered and sent to the command center.</p></div><div className="siren"><Siren size={34}/></div></div><form onSubmit={submit}><label>Emergency category<select value={category} onChange={e=>setCategory(e.target.value as Category)}><option>FLOOD</option><option>FIRE</option><option>MEDICAL</option><option>BUILDING COLLAPSE</option><option>ROAD BLOCKAGE</option><option>OTHER</option></select></label><label>What is happening?<textarea value={text} onChange={e=>setText(e.target.value)} rows={6}/></label><div className="row"><button type="button" className="tool" onClick={voice}><Mic/> {recording?"Listening…":"Voice input"}</button><button type="button" className="tool" onClick={locate}><MapPin/> Use my location</button><button type="button" className="tool"><Upload/> Evidence</button></div><button className="send" disabled={loading||sent}><Send/> {loading?"SENDING SOS…":sent?"SOS SENT ✓":"SEND SOS"}</button></form>{result&&<div className="result"><div className="result-top"><b>✓ SOS SENT SUCCESSFULLY</b><span>{result.priority} • PENDING • WAITING FOR DISPATCHER</span></div><p><strong>Location:</strong> {result.location.location_text}</p><p><strong>Status:</strong> Your SOS has been sent successfully and is now waiting for dispatcher acceptance.</p><p><strong>Priority reason:</strong> {result.analysis.reasons.join(" • ")}</p>{result.matched&&<p><strong>Cluster:</strong> {Math.round(result.distance_m)}m away • report added to existing incident</p>}<small>Incident: {result.incident_id} • Report: {result.report_id}</small></div>}</section></main>
}