create extension if not exists pgcrypto;
create table if not exists incidents(id uuid primary key default gen_random_uuid(),title text not null,category text not null,description text not null,latitude double precision not null,longitude double precision not null,location_text text not null,severity text not null check(severity in('CRITICAL','HIGH','MEDIUM','LOW')),severity_score int not null default 0,severity_reasons jsonb not null default '[]'::jsonb,report_count int not null default 0,status text not null default 'NEW' check(status in('NEW','TRIAGED','DISPATCHED','RESOLVED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists reports(id uuid primary key default gen_random_uuid(),incident_id uuid references incidents(id) on delete cascade,description text not null,source text not null check(source in('text','voice','image')),latitude double precision not null,longitude double precision not null,location_text text not null,severity text not null,severity_score int not null,severity_reasons jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
create table if not exists rescue_units(id uuid primary key default gen_random_uuid(),name text not null,type text not null,latitude double precision not null,longitude double precision not null,status text not null check(status in('AVAILABLE','ASSIGNED','EN_ROUTE','ON_SCENE','COMPLETED')),current_incident_id uuid references incidents(id) on delete set null,updated_at timestamptz not null default now());
create table if not exists dispatches(id uuid primary key default gen_random_uuid(),incident_id uuid references incidents(id) on delete cascade,unit_id uuid references rescue_units(id) on delete cascade,assigned_at timestamptz not null default now(),status text not null default 'ASSIGNED',completed_at timestamptz);
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),action text not null,entity_type text not null,entity_id uuid,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists incidents_status_idx on incidents(status);create index if not exists reports_incident_idx on reports(incident_id);create index if not exists units_status_idx on rescue_units(status);
alter table incidents enable row level security;alter table reports enable row level security;alter table rescue_units enable row level security;alter table dispatches enable row level security;alter table audit_logs enable row level security;
drop policy if exists "demo incidents read" on incidents;create policy "demo incidents read" on incidents for select to anon,authenticated using(true);
drop policy if exists "demo incidents insert" on incidents;create policy "demo incidents insert" on incidents for insert to anon,authenticated with check(true);
drop policy if exists "demo incidents update" on incidents;create policy "demo incidents update" on incidents for update to anon,authenticated using(true) with check(true);
drop policy if exists "demo reports read" on reports;create policy "demo reports read" on reports for select to anon,authenticated using(true);
drop policy if exists "demo reports insert" on reports;create policy "demo reports insert" on reports for insert to anon,authenticated with check(true);
drop policy if exists "demo units read" on rescue_units;create policy "demo units read" on rescue_units for select to anon,authenticated using(true);
drop policy if exists "demo units update" on rescue_units;create policy "demo units update" on rescue_units for update to anon,authenticated using(true) with check(true);
drop policy if exists "demo dispatch read" on dispatches;create policy "demo dispatch read" on dispatches for select to anon,authenticated using(true);
drop policy if exists "demo dispatch insert" on dispatches;create policy "demo dispatch insert" on dispatches for insert to anon,authenticated with check(true);
drop policy if exists "demo audit read" on audit_logs;create policy "demo audit read" on audit_logs for select to anon,authenticated using(true);
drop policy if exists "demo audit insert" on audit_logs;create policy "demo audit insert" on audit_logs for insert to anon,authenticated with check(true);
create or replace function process_sos(p_description text,p_source text,p_category text,p_latitude double precision,p_longitude double precision,p_location_text text,p_severity text,p_severity_score int,p_severity_reasons jsonb) returns jsonb language plpgsql as $$
declare i incidents; r reports; dist double precision; title text; begin
select x.*,111320*sqrt(power((x.latitude-p_latitude),2)+power((x.longitude-p_longitude)*cos(radians(p_latitude)),2)) as d into i from incidents x where x.status<>'RESOLVED' and x.category=p_category and 111320*sqrt(power((x.latitude-p_latitude),2)+power((x.longitude-p_longitude)*cos(radians(p_latitude)),2))<=500 order by d limit 1;
if i.id is not null then dist:=111320*sqrt(power((i.latitude-p_latitude),2)+power((i.longitude-p_longitude)*cos(radians(p_latitude)),2));update incidents set report_count=report_count+1,severity_score=greatest(severity_score,p_severity_score),severity=case when p_severity_score>severity_score then p_severity else severity end,severity_reasons=case when p_severity_score>severity_score then p_severity_reasons else severity_reasons end,updated_at=now() where id=i.id;else
title:=initcap(lower(p_category))||' near '||p_location_text;insert into incidents(title,category,description,latitude,longitude,location_text,severity,severity_score,severity_reasons,report_count,status) values(title,p_category,p_description,p_latitude,p_longitude,p_location_text,p_severity,p_severity_score,p_severity_reasons,0,'TRIAGED') returning * into i;dist:=null;end if;
insert into reports(incident_id,description,source,latitude,longitude,location_text,severity,severity_score,severity_reasons) values(i.id,p_description,p_source,p_latitude,p_longitude,p_location_text,p_severity,p_severity_score,p_severity_reasons) returning * into r;
update incidents set report_count=(select count(*) from reports where incident_id=i.id),updated_at=now() where id=i.id;
insert into audit_logs(action,entity_type,entity_id,details) values('SOS_PROCESSED','incident',i.id,jsonb_build_object('matched',dist is not null,'distance_m',dist,'category',p_category));
return jsonb_build_object('incident_id',i.id,'report_id',r.id,'matched',dist is not null,'distance_m',dist);
end $$;
create or replace function assign_nearest_unit(p_incident_id uuid) returns jsonb language plpgsql as $$
declare i incidents;u rescue_units;d double precision;dispatch_id uuid;begin select * into i from incidents where id=p_incident_id for update;if i.id is null then raise exception 'Incident not found';end if;
select x.*,111320*sqrt(power((x.latitude-i.latitude),2)+power((x.longitude-i.longitude)*cos(radians(i.latitude)),2)) as d into u from rescue_units x where x.status='AVAILABLE' order by d limit 1;
if u.id is null then return jsonb_build_object('ok',false,'message','No available rescue units');end if;
d:=111320*sqrt(power((u.latitude-i.latitude),2)+power((u.longitude-i.longitude)*cos(radians(i.latitude)),2));update rescue_units set status='ASSIGNED',current_incident_id=i.id,updated_at=now() where id=u.id;insert into dispatches(incident_id,unit_id,status) values(i.id,u.id,'ASSIGNED') returning id into dispatch_id;update incidents set status='DISPATCHED',updated_at=now() where id=i.id;insert into audit_logs(action,entity_type,entity_id,details) values('UNIT_DISPATCHED','incident',i.id,jsonb_build_object('unit_id',u.id,'distance_m',d));return jsonb_build_object('ok',true,'unit_id',u.id,'unit_name',u.name,'distance_m',d,'dispatch_id',dispatch_id);end $$;
grant execute on function process_sos(text,text,text,double precision,double precision,text,text,int,jsonb) to anon,authenticated;grant execute on function assign_nearest_unit(uuid) to anon,authenticated;